name: Scrape Twitch Data

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper
        run: |
          curl -X GET "${{ secrets.VERCEL_URL }}/api/cron/scrape" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            --max-time 60
